server:
  port: 8002
  servlet:
    context-path: /api/short-link/admin/v1

spring:
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123321